version: '3.0'

services:
  sor-db:
    container_name: sor-db-container
    image: mysql:latest
    ports:
      - 3307:3306
    volumes:
      - /Users/ybzhou/sql-data/sor-data-container:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=sor
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
  sor:
    container_name: sor-container
    image: felix/sor
    depends_on:
      - sor-db
    ports:
      - 8081:8081
    environment:
      - DATABASE_HOST=sor-db
      - DATABASE_PORT=3306
      - DATABASE_USER=user
      - DATABASE_PASSWORD=password
      - DATABASE_NAME=sor
  sod-db:
    container_name: sod-db-container
    image: mysql:latest
    ports:
      - 3308:3306
    volumes:
      - /Users/ybzhou/sql-data/sod-data-container:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=sod
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
  sod:
    container_name: sod-container
    image: felix/sod
    depends_on:
      - sod-db
      - sor
    ports:
      - 8082:8082
    environment:
      - DATABASE_HOST=sod-db
      - DATABASE_PORT=3306
      - DATABASE_USER=user
      - DATABASE_PASSWORD=password
      - DATABASE_NAME=sod
      - APPROVAL_HOST=sor
      - APPROVAL_PORT=8081
      - APPROVAL_PATH=images
  nginx-proxy:
    container_name: nginx-proxy
    image: felix/nginx:latest
    volumes:
      - /Users/ybzhou/ThoughtWorks/Training/gaint-training/services-eureka/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
    links:
      - sor
      - sod

