version: '3.0'

services:
  sor-db:
    image: mysql:latest
    ports:
      - 3307:3306
    volumes:
      - /Users/ybzhou/sql-data/sor-data-container:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=sor
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
  sor:
    image: felix/sor
    depends_on:
      - sor-db
    ports:
      - 8081:8081
    environment:
      - DATABASE_HOST=sor-db
      - DATABASE_PORT=3306
      - DATABASE_USER=user
      - DATABASE_PASSWORD=password
      - DATABASE_NAME=sor
  sod-db:
    image: mysql:latest
    ports:
      - 3308:3306
    volumes:
      - /Users/ybzhou/sql-data/sod-data-container:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=sod
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
  sod:
    image: felix/sod
    depends_on:
      - sod-db
      - sor
    ports:
      - 8082:8082
    environment:
      - DATABASE_HOST=sod-db
      - DATABASE_PORT=3306
      - DATABASE_USER=user
      - DATABASE_PASSWORD=password
      - DATABASE_NAME=sod
      - APPROVAL_HOST=sor
      - APPROVAL_PORT=8081
      - APPROVAL_PATH=images


