spring:
  application:
    name: sod
  profiles:
    active: dev
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQLDialect
    open-in-view: false
  output:
    ansi:
      enabled: always
