version: '3.0'

services:
  sod-db:
    image: mysql:latest
    ports:
      - 3308:3306
    volumes:
      - /Users/ybzhou/sql-data/sod-data-container:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=sod
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
  sod:
    image: felix/sod
    depends_on:
      - sod-db
    ports:
      - 8082:8082
    environment:
      - DATABASE_HOST=sod-db
      - DATABASE_PORT=3306
      - DATABASE_USER=user
      - DATABASE_PASSWORD=password
      - DATABASE_NAME=sod
